# Redis backend

appName: guestbook   # ← always "guestbook" for the stable service name

canary:
  enabled: false
  stableWeight: 90
  canaryWeight: 10
  stableServiceName: guestbook-frontend        # what to call stable in the splitter
  canaryServiceName: guestbook-canary-frontend # what to call canary in the splitter

redis:
  enabled: true
  image: redis:7.2
  port: 6379
  replicas: 1
  serviceName: redis-leader
  followerServiceName: redis-follower
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

# Guestbook frontend
frontend:
  image: gcr.io/google-samples/gb-frontend:v5
  port: 80
  replicas: 3
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "250m"

# Ingress (Traefik)
ingress:
  enabled: true
  host: guestbook.local
  entryPoint: web