apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secret
type: Opaque
stringData:
  mysql-root-password: {{ .Values.mysql.rootPassword }}
  mysql-password: {{ .Values.mysql.password }}