apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  namespace: default
spec:
  template:
    metadata:
      {{- if not .Values.wordpress.canary.enabled }}
      name: {{ .Release.Name }}-wordpress-stable
      {{- end }}
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: wordpress
          image: {{ if .Values.wordpress.canary.enabled }}{{ .Values.wordpress.canary.image }}{{ else }}{{ .Values.wordpress.image }}{{ end }}
          ports:
            - containerPort: {{ .Values.wordpress.port }}
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ .Release.Name }}-mysql:{{ .Values.mysql.port }}"
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.mysql.database }}
            - name: WORDPRESS_DB_USER
              value: {{ .Values.mysql.user }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secret
                  key: mysql-password
  traffic:
    {{- if .Values.wordpress.canary.enabled }}
    - latestRevision: true
      percent: {{ .Values.wordpress.canary.trafficPercent }}
    - latestRevision: false
      revisionName: {{ .Release.Name }}-wordpress-stable
      percent: {{ sub 100 .Values.wordpress.canary.trafficPercent }}
    {{- else }}
    - latestRevision: true
      percent: 100
    {{- end }}