{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-redis
  labels:
    app: {{ .Values.appName }}-redis
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}-redis
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            requests:
              memory: {{ .Values.redis.resources.requests.memory }}
              cpu: {{ .Values.redis.resources.requests.cpu }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory }}
              cpu: {{ .Values.redis.resources.limits.cpu }}
{{- end }}